### ISSUE TITLE
Can't use hprose-ruby?

### ISSUE THREAD

**Issue by sail1972** [hprose/hprose-ruby#2]
Hi Dear,

I installed hprose gem version 1.4.13  in my computer. When I ran the example server.rb, something errors happened.

``` bash
gdmxiaofanli:hprose-test sail$ gem -v
1.8.23.2
gdmxiaofanli:hprose-test sail$ ruby -v
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-darwin13.4.0]
gdmxiaofanli:hprose-test sail$ gem install hprose
Fetching: hprose-1.4.13.gem (100%)
Successfully installed hprose-1.4.13
1 gem installed
Installing ri documentation for hprose-1.4.13...
Installing RDoc documentation for hprose-1.4.13...
gdmxiaofanli:hprose-test sail$ ruby server.rb
/Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- uuidtools (LoadError)
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/hprose-1.4.13/lib/hprose/io.rb:24:in `<top (required)>'
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/hprose-1.4.13/lib/hprose.rb:43:in `const_get'
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/hprose-1.4.13/lib/hprose.rb:43:in `<top (required)>'
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /Users/sail/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from server.rb:3:in `<main>'
```

It seems that hprose gem can't be required in server.rb, why?  Anyone help me?

**Comment by sail1972** [comment]
I found the answer, it must install the uuidtools gem before.
